services:
  pocketbase:
    build:
      dockerfile: ops/Dockerfile.Pocketbase
      context: .
    container_name: rehab-pocketbase
    expose:
      - "8090"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY:-your-secret-key-here}

  frontend:
    build:
      dockerfile: ops/Dockerfile.Frontend
      context: .
      args:
        - VITE_PB_URL=${VITE_PB_URL}
    container_name: rehab-frontend
    expose:
      - "80"
