FROM node:22-alpine AS builder

ARG VITE_PB_URL
ENV VITE_PB_URL=$VITE_PB_URL

WORKDIR /app

COPY ../package*.json ./
COPY ../nginx.conf ./

RUN npm install

COPY ../ .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
